force-app/main/default/objects/Custom_Email_Message__c/Custom_Email_Message__c.object-meta.xml
<CustomObject>
    <label>Custom Email Message</label>
    <nameField>
        <displayFormat>MSG-{000000}</displayFormat>
        <label>Custom Email Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Email Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Email_Message__c/fields/Message_Id__c.field-meta.xml
<CustomField>
    <fullName>Message_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Message Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Custom_Email_Message__c/fields/Message_Text__c.field-meta.xml
<CustomField>
    <fullName>Message_Text__c</fullName>
    <label>Message Text</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Email_Message__c/fields/Sender_Email__c.field-meta.xml
<CustomField>
    <fullName>Sender_Email__c</fullName>
    <label>Sender Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Custom_Email_Message__c/fields/Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Sender_Name__c</fullName>
    <label>Sender Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/main/selector/CustomEmailMessageSelector.cls
public with sharing class CustomEmailMessageSelector {
	public static List<Custom_Email_Message__c> selectMessages() {
		Map<Id, Custom_Email_Message__c> messageIdToMessageMap = new Map<Id, Custom_Email_Message__c>(
			[
				SELECT Id
				FROM Custom_Email_Message__c
				ORDER BY CreatedDate DESC
				LIMIT 100
			]
		);

		return messageIdToMessageMap;
	}

	public static List<Custom_Email_Message__c> selectMessagesWithOffset(Integer offset) {
		return [
			SELECT Id, Message_Id__c, Subject__c, Sender_Name__c, Sender_Email__c, Message_Text__c
			FROM Custom_Email_Message__c
			ORDER BY CreatedDate DESC
			LIMIT 50
			OFFSET :offset
		];
	}
}